version: "3.9"
services:
  api:
    build: .
    command: npm run dev
    ports: ["3000:3000"]
    env_file: .env
    volumes: [".:/app"]
    depends_on: [mongo]
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: appdb
  # Descomenta si quieres Postgres
  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   ports: ["5432:5432"]
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: appdb
